name: parse-pkgbuild

on:
  push:
  workflow_dispatch:

jobs:
  parse:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: python git mingw-w64-x86_64-toolchain mingw-w64-i686-toolchain
          update: true

      - run: |
          curl -L --retry 5 -o srcinfo.json 'https://github.com/msys2/MINGW-packages/releases/download/pkgbuild-cache/srcinfo.json'
          python ci-parse-pkgbuild.py --time-limit 19800 . srcinfo.json

      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: srcinfo.json

  upload:
    needs: parse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: result

      - uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: pkgbuild-cache
          rm: true
          files: srcinfo.json